### ISSUE TITLE
Very interesting! How to expand for different  European tournaments?

### ISSUE THREAD

**Issue by rdibella** [axelmierczuk/sportyfin#1]
How can we expand to other football tournaments like Champions League, Europa League and Seria A, La Liga, Bundesliga, Ligue 1?

It seems to me that from the page you get the streams you can also get the other tournaments so it should be pretty easy right?

**Comment by axelmierczuk** [comment]
So right now the program filters with English games only. I can remove the filter so to scrape for all European football games, but the difficulty with that is that the website that is being scraped has mediocre football streams. The best solution would be to find a different website to scrape... which I will do eventually... but for now, I'll remove the filter.
