### ISSUE TITLE
formatedStartDate Error can't start docker container.

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [axelmierczuk/sportyfin#5]
```
[+] COLLECTING ENGLISH FOOTBALL STREAMING LINKS
[-] 'formatedStartDate'
```

**Comment by axelmierczuk** [comment]
Can you check version when running container? If it is 1.0.7 it should be fine

**Comment by cookie-monster-bit** [comment]
Ahh, it's Version: 1.0.3. Can you push an update to the docker container?

**Comment by AD1995** [comment]
Currently having the same error using 1.0.3 from dockerhub. Any chance 1.0.7 could be pushed?

**Comment by axelmierczuk** [comment]
Docker container version has been updated. Completely slipped my mind until this morning. Sorry all!!
