### ISSUE TITLE
Arm Support

### ISSUE THREAD

**Issue by LennoINS** [axelmierczuk/sportyfin#6]
Hi i tried setting up Sportyfin on my webserver (raspberry pi 4) to use in combination with Jellyfin. Sadly there is no ARM image available..

**Comment by LennoINS** [comment]
Trying Pip installation gives me the following error any ideas?


root@raspberrypi:/# pip install sportyfin --no-binary=sportyfin
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting sportyfin
  Using cached https://files.pythonhosted.org/packages/ef/28/1676349c1b0eb5ad187020dde191730907aedf1af91a562cde29d2ac5cf0/sportyfin-1.0.7.tar.gz
Collecting async-generator (from sportyfin)
  Using cached https://files.pythonhosted.org/packages/cf/2f/0577dc1ebcee37f5b4ace6f32da5bd2b2dc9073d82186143b75259b52123/async_generator-1.8.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Z9lkm9/async-generator/setup.py", line 5, in <module>
        from async_generator import __version__
      File "async_generator/__init__.py", line 1, in <module>
        from .impl import (
      File "async_generator/impl.py", line 98
        async def yield_(value=None):
                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Z9lkm9/async-generator/

**Comment by axelmierczuk** [comment]
This is not relevant to the program itself.
